= vpro-tomcat
:toc:

Generic tomcat base image that:

. Separates CATALINA_BASE
. Prepares for a proxy server that arranges https, and more customized tomcat configuration.
. contains some custom scripts
    - 'aptime': command line utility to show what's running
    - /usr/local/catalina-base/bin/start.sh custom start up script. Arranging gracefull shutdown. 
    - /usr/local/catalina-base/bin/setenv.sh  picked up by tomcat
    - /usr/local/catalina-base/bin/jmx.sh included by setenv.sh, but can also be used remotely for easy figuring out that relevant ports to forward are


You can build this locally like so:

----
docker build -t vpro/tomcat:latest .
----

Use e.g. with a Dockerfile like this"

----
ARG NAME=media-server

FROM vpro/tomcat:latest

RUN apt-get -y install openssh-client sshpass

----

which then can be build this way:

.example for media-server
[source,bash]
----
~/npo/media/trunk$ docker build  —-build-arg PROJECT_VERSION=`mvn help:evaluate -Dexpression=project.version -q -DforceStdout` -t media-server media-server
----

.example for api-server
[source,bash]
----
~/npo/api/trunk$ docker build --build-arg PROJECT_VERSION=`mvn help:evaluate -Dexpression=project.version -q -DforceStdout` -t api-server api-server
----

== Versions

|===
|version | tomcat | java | remarks
| 5.x | 10.x | 21 | javax -> jakarta migrations (TODO)
| 4.x | >= 9.0.81 | 21  |
| 3.x | 9.x | 17 | first one named vpro/tomcat?
| 2.x | 9.x | 17 | 
| 1.x | 9.x | 8 |
|===

