= vpro-tomcat
:toc:

image:https://github.com/vpro/tomcat/actions/workflows/docker-publish.yml/badge.svg[Build Status,link=https://github.com/vpro/tomcat/actions/workflows/docker-publish.yml]


Generic tomcat base image that:

. Separates CATALINA_BASE
. Prepares for a proxy server that arranges https, and more customized tomcat configuration.
. contains some custom scripts
    - 'aptime': command line utility to show what's running
    - /usr/local/catalina-base/bin/start.sh custom start up script. Arranging gracefull shutdown.
    - /usr/local/catalina-base/bin/setenv.sh  picked up by tomcat
    - /usr/local/catalina-base/bin/jmx.sh included by setenv.sh, but can also be used remotely for easy figuring out what the relevant ports to forward are
    - has eu-central certificates in cacerts
. Recognizes some more other environment variables
  - `CATALINA_DEBUG`: <true|false> If true jpda debugging is enabled. Only accessible from localhost so it would require tunneling to access it.
  - `CATALINA_DEBUG_EVAL`: e.g. '`[[ $POD_NAME == *-0 ]] && echo true || echo false'` to have debug enable only on first pod.
 -

It is built and released using github actions, and available https://github.com/vpro/tomcat/pkgs/container/tomcat[via github packages]

== Building locally

You can build this locally like so:

----
docker build -t vpro/tomcat:latest .
----

Use e.g. with a Dockerfile like this:

----
ARG NAME=media-server

FROM ghcr.io/vpro/tomcat:latest

RUN apt-get -y install openssh-client sshpass
----

which then can be build this way:

.example for media-server
[source,bash]
----
~/npo/media/trunk$ docker build  —-build-arg PROJECT_VERSION=`mvn help:evaluate -Dexpression=project.version -q -DforceStdout` -t media-server media-server
----

.example for api-server
[source,bash]
----
~/npo/api/trunk$ docker build --build-arg PROJECT_VERSION=`mvn help:evaluate -Dexpression=project.version -q -DforceStdout` -t api-server api-server
----

== Versions

|===
|version | tomcat | java | remarks
| >= 11.0 | 11.x | 25 | 
| >= 10.36 | 10.x | 25 | 
| >= 10.18 | 10.x | 21 | using jre rather than jdk, which makes the image smaller.
| >= 10.10 | 10.x | 21 | available as ghcr.io/vpro/tomcat:10.x
| >= 10.7 | 10.x | 21 | versions for cph5
| >= 10.6.2 | 10.x | 21 | chp4 version available as ghcr.io/vpro/tomcat:10.6.x
| 10.6.* | 10.x | 21 | running for chp4, mainly related to chown-settings for certain directories
| 10.x | 10.x | 21 |
| 9.x | >= 9.0.81 | 21  |
| 4.x | 9.x | 21  |
| 3.x | 9.x | 17 | first one named vpro/tomcat?
| 2.x | 9.x | 17 |
| 1.x | 9.x | 8 |
|===


